create table USER_PROFILE (
  ID bigint generated by default as identity,
  IS_ACTIVE boolean,
  LAST_UPDATE date,
  UPDATED_BY varchar(255),
  VALID_FROM date,
  VALID_TO date,
  CITY varchar(255),
  STREET_NAME varchar(255),
  STREET_NUMBER INTEGER,
  EMAIL varchar(255),
  IMG_PATH varchar(255),
  NAME varchar(255),
  NICKNAME varchar(255),
  PASSWORD varchar(255),
  SURNAME varchar(255),
  ROLE integer, primary key (id)
);

alter table USER_COMMENT add constraint FK_USER_PROFILE foreign key (user_id_ref) references USER_PROFILE;
