create table USER_PROFILE (
  id bigint generated by default as identity,
  is_deleted boolean,
  last_update date,
  updated_by varchar(255),
  valid_from date,
  valid_to date,
  EMAIL varchar(255),
  IMG_PATH varchar(255),
  NAME varchar(255),
  NICKNAME varchar(255),
  PASSWORD varchar(255),
  SURNAME varchar(255),
  ROLE integer, primary key (id)
);

alter table USER_COMMENT add constraint FK_USER_PROFILE foreign key (user_id_ref) references USER_PROFILE;
