create table SOCIAL_PROFILE (
  ID bigint generated by default as identity,
  IS_ACTIVE boolean,
  LAST_UPDATE date,
  UPDATED_BY varchar(255),
  VALID_FROM date,
  VALID_TO date,
  PROFILE_NAME varchar(255),
  PROFILE_URL varchar(255), primary key (id)
);


alter table USER_PROFILE add SOCIAL_ID_REF bigint;
alter table USER_PROFILE add constraint FK_SOCIAL_PROFILE foreign key (SOCIAL_ID_REF) references SOCIAL_PROFILE;
